### ISSUE TITLE
Bug in nginx.rake

### ISSUE THREAD

**Issue by dentarg** [twingly/capistrano-twingly#6]
At the end of `bundle exec cap staging deploy` I got:

``` sh
cap aborted!
undefined local variable or method `app_name' for #<SSHKit::Backend::Netssh:0x007fcb9bc88f70>
/Users/dentarg/twingly/capistrano-twingly/lib/capistrano/twingly/tasks/nginx.rake:43:in `block (4 levels) in <top (required)>'
/Users/dentarg/.gem/ruby/2.0.0/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/dentarg/.gem/ruby/2.0.0/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/dentarg/.gem/ruby/2.0.0/gems/sshkit-1.3.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => deploy:nginx:upload_config
(See full trace by running task with --trace)
```

Likely it has something to do with changes introduced in 756883abd93acd1ee7c3a2dff851aeaf8e60dadf.
